language: objective-c

rvm:
  - "system; export CEDAR_SDK_VERSION=5.0 #"
  - "system; export CEDAR_SDK_VERSION=5.1 #"
  - "system; export CEDAR_SDK_VERSION=6.0 #"
  - "system; export CEDAR_SDK_VERSION=6.1 #"
  - "system; export CEDAR_SDK_VERSION=7.0 #"

env:
  matrix:
    - CEDAR_SDK_RUNTIME_VERSION="5.0"
    - CEDAR_SDK_RUNTIME_VERSION="5.1"
    - CEDAR_SDK_RUNTIME_VERSION="6.0"
    - CEDAR_SDK_RUNTIME_VERSION="6.1"
    - CEDAR_SDK_RUNTIME_VERSION="7.0"

script: rake
